<?php

namespace MovieWall\ApiBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * WatchlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends DocumentRepository
{
}